config/routes.rb
LearnList::Application.routes.draw do
  resources :schools
  resources :sections
  resources :courses
  resources :subjects
  resources :teachers
  resources :students
  resources :learning_links
  resources :units

match 'home' => 'learning_links#add'

root :to => "learning_links#add"

end

app/models/course.rb
class Course < ActiveRecord::Base

attr_accessible :course_name

belongs_to :subjects

end

app/models/do_it.rb
class DoIt < ActiveRecord::Base

attr_accessible :do_it_title

belongs_to :learning_links


end

app/models/learning_link.rb
class LearningLink < ActiveRecord::Base

attr_accessible :learn_title
attr_accessible :learn_url

belongs_to :subtopic
belongs_to :topic
belongs_to :unit
has_many :do_its

end

app/models/school.rb
class School < ActiveRecord::Base

  validates :school_name, :presence => true

  attr_accessible :school_name

  has_many :sections

  before_save :titlecase
	
  private

	def titlecase
	  self.school_name = self.school_name.titleize
	end
  
end

app/models/section.rb
class Section < ActiveRecord::Base

belongs_to :course
belongs_to :teacher
belongs_to :school
has_and_belongs_to_many :students
has_many :units
has_many :learning_links

end

app/models/student.rb
class Student < ActiveRecord::Base

attr_accessible :first_name, :last_name

has_and_belongs_to_many :sections

end

app/models/subject.rb
class Subject < ActiveRecord::Base

attr_accessible :subject_name
has_many :courses


end

app/models/subtopic.rb
class Subtopic < ActiveRecord::Base

attr_accessible :subtopic_name

has_many :learning_links

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
attr_accessible :first_name, :last_name
has_many :sections

end

app/models/topic.rb
class Topic < ActiveRecord::Base

attr_accessible :topic_name

has_many :learning_links

end

app/models/unit.rb
class Unit < ActiveRecord::Base

attr_accessible :unit_name
has_many :learning_links

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController  
  def new
    @course = Course.new
  end


  def create
    @course = Course.new(params[:course])

    if @course.save
      flash[:notice] = "Your course was successfully added!"
      redirect_to courses_path

    else
      render :new
      flash[:alert] = "Please make sure all fields are filled in and try again."
    end
  end

  def index
    @courses = Course.all 
  end

  def update
    @courses = Courses.find(params[:id])
    if @course.update_attributes(params[:course])
      flash[:notice] = "Your course was successfully updated."
      redirect_to course_path
    else
      render :edit
    end
  end

  def show
    @course = Course.find(params[:id])
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy
    flash[:notice] = "Your course was successfully deleted."
    redirect_to courses_path
  end

end

app/controllers/learning_links_controller.rb
class LearningLinksController < ApplicationController

	def new
    @learning_link = LearningLink.new
  end

  def create
    if @learning_link.save
      flash[:notice] = "Link Added!"
      redirect_to learning_links_path
    else
      flash[:alert] = "Oops! Something went wrong."
      render :new
    end
  end





end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController  
  def new
    @school = School.new
  end


  def create
    @school = School.new(params[:school])

    if @school.save
      flash[:notice] = "Your school was successfully added!"
      redirect_to schools_path

    else
      render :new
      flash[:alert] = "Please make sure all fields are filled in and try again."
    end
  end

  def index
    @schools = School.all 
  end

  def update
    @schools = Schools.find(params[:id])
    if @school.update_attributes(params[:school])
      flash[:notice] = "Your school was successfully updated."
      redirect_to school_path
    else
      render :edit
    end
  end

  def show
    @school = School.find(params[:id])
  end

  def destroy
    @school = School.find(params[:id])
    @school.destroy
    flash[:notice] = "Your school was successfully deleted."
    redirect_to schools_path
  end

end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController

def create
    if @section.save
      flash[:notice] = "Section Added!"
      redirect_to sections_path
    else
      flash[:alert] = "Oops! Something went wrong."
      render :new
    end
  end



end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController  
  def new
    @subject = Subject.new
  end


  def create
    @subject = Subject.new(params[:subject])

    if @subject.save
      flash[:notice] = "Your subject was successfully added!"
      redirect_to subjects_path

    else
      render :new
      flash[:alert] = "Please make sure all fields are filled in and try again."
    end
  end

  def index
    @subjects = Subject.all 
  end

  def update
    @subjects = Subjects.find(params[:id])
    if @subject.update_attributes(params[:subject])
      flash[:notice] = "Your subject was successfully updated."
      redirect_to subject_path
    else
      render :edit
    end
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id])
    @subject.destroy
    flash[:notice] = "Your subject was successfully deleted."
    redirect_to courses_path
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController  
  def new
    @unit = Unit.new
  end

  def create
    @unit = Unit.new(params[:unit])

    if @unit.save
      flash[:notice] = "Your unit was successfully added!"
      redirect_to units_path

    else
      render :new
      flash[:alert] = "Please make sure all fields are filled in and try again."
    end
  end

  def index
    @units = Unit.all 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/index.html.erb
<% provide :title, 'Schools' %>

<table class='table'>
  <thead class='section'>
    <tr>
      <th>Course Name</th>
      <th></th>
    </tr>
  </thead>
  <% @courses.each do |course| %>
    <tr>
      <td><%= link_to "#{course.course_name}", courses_path(:course_id => course.id) %></td>
      <td><%= link_to 'Delete', course, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini' %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add a Course', new_course_path, :class => 'btn btn-primary' %></p>

app/views/courses/new.html.erb
<% provide :title, "Add a new course" %>

<%= render :partial => 'layouts/errors', :locals => {:object => @course} %>

<%= form_for Course.new do |f| %>
  <%= f.label :course_name %>
  <%= f.text_field :course_name, :autofocus => true %>

  <%= f.submit "Add", :class => 'btn btn-primary' %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-error">
    <h3>Please correct these problems:</h3>
    <h4><ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul></h4>
  </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:error] %>
  <div class="alert alert-error"><%= flash[:error] %></div>
<% end %>

<% if flash[:alert] %>
  <div class="alert"><%= flash[:alert] %></div>
<% end %>

<% if flash[:notice] %>
  <div class="alert alert-info"><%= flash[:notice] %></div>
<% end %>

<% if flash[:success] %>
  <div class="alert alert-success"><%= flash[:success] %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LearnList</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/learning_links/_form.html.erb
  <!-- # <%= render :partial => 'layouts/errors', :locals => {:object => @tool} %> -->

<%= form_for @learning_list do |f| %>

 <%= f.label :section %>
  <%= f.collection_select(:section_id, @sections, :id, :section_name, :include_blank => true) if @sections %>
  <!-- # <%= link_to "Add Subject", new_subject_path, :class => "btn btn-mini" %>

  # <%= f.label :name %>
  # <%= f.text_field :name, :autofocus => true %>

  # <%= f.label :location %>
  # <%= f.text_field :location, :placeholder =>"http://" %>

  # <%= f.label :subject %>
  # <%= f.collection_select(:subject_id, @subjects, :id, :category, :include_blank => true) if @subjects %>
  # <%= link_to "Add Subject", new_subject_path, :class => "btn btn-mini" %>


  # <%= f.label :type %>
  # <%= f.collection_select(:type_id, @types, :id, :format, :include_blank => true) if @types %>
  # <%= link_to "Add Type", new_type_path, :class => "btn btn-mini" %>
        

  # <%= f.label :level %>
  # <%= f.collection_select(:level, Tool::LEVEL, :to_s, :to_s, :include_blank => true) %>

  # <%= f.label :cost %>
  # <%= f.collection_select(:cost, Tool::COST, :to_s, :to_s, :include_blank => true) %>


  # <%= f.submit "Save", :class => 'btn btn-primary' %>

  # <% end %> -->

app/views/learning_links/new.html.erb
<% provide :title, "Add a new learning link." %>

<%= form_for LearningLink.new do |f| %>

  <%= f.label :Unit %>
  <%= f.text_field :unit %>

  <%= f.label :Topic %>
  <%= f.text_field :topic %>

  <%= f.label :Subtopic %>
  <%= f.text_field :subtopic %>

  <%= f.label :Learning_Link_Title %>
  <%= f.text_field :learn_title, :autofocus => true %>

  <%= f.label :Link %>
  <%= f.text_field :learn_url %>

  <%= f.submit "Add", :class => 'btn btn-primary' %>
<% end %>

app/views/schools/index.html.erb
<% provide :title, 'Schools' %>

<table class='table'>
  <thead class='section'>
    <tr>
      <th>School Name</th>
      <th></th>
    </tr>
  </thead>
  <% @schools.each do |school| %>
    <tr>
      <td><%= link_to "#{school.school_name}", schools_path(:school_id => school.id) %></td>
      <td><%= link_to 'Delete', school, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini' %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add a School', new_school_path, :class => 'btn btn-primary' %></p>

app/views/schools/new.html.erb
<% provide :title, "Add a new school" %>

<%= render :partial => 'layouts/errors', :locals => {:object => @school} %>

<%= form_for School.new do |f| %>
  <%= f.label :school_name %>
  <%= f.text_field :school_name, :autofocus => true %>

  <%= f.submit "Add", :class => 'btn btn-primary' %>
<% end %>

app/views/subjects/index.html.erb
<% provide :title, 'Subjects' %>

<table class='table'>
  <thead class='section'>
    <tr>
      <th>Subject Name</th>
      <th></th>
    </tr>
  </thead>
  <% @subjects.each do |subject| %>
    <tr>
      <td><%= link_to "#{subject.subject_name}", subjects_path(:subject_id => subject.id) %></td>
      <td><%= link_to 'Delete', subject, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini' %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add a Subject', new_subject_path, :class => 'btn btn-primary' %></p>

app/views/subjects/new.html.erb
<% provide :title, "Add a new subject" %>

<%= render :partial => 'layouts/errors', :locals => {:object => @subject} %>

<%= form_for Subject.new do |f| %>
  <%= f.label :subject_name %>
  <%= f.text_field :subject_name, :autofocus => true %>

  <%= f.submit "Add", :class => 'btn btn-primary' %>
<% end %>

app/views/units/new.html.erb
<% provide :title, "Add a new unit" %>

<%= form_for Unit.new do |f| %>
  <%= f.label :unit_name %>
  <%= f.text_field :unit_name, :autofocus => true %>

  <%= f.submit "Add", :class => 'btn btn-primary' %>
<% end %>


<table class='table'>
  <thead class='unit'>
    <tr>
      <th>Unit Name</th>
      <th></th>
    </tr>
  </thead>
  <% @units.each do |unit| %>
    <tr>
      <td><%= link_to "#{unit.unit_name}", units_path(:unit_id => unit.id) %></td>
      <td><%= link_to 'Delete', unit, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-mini' %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Add a Unit', new_unit_path, :class => 'btn btn-primary' %></p>